version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      ROOT_USERNAME: 
      ROOT_PASSWORD: 
    volumes:
      - /home/mongodb/data/db:/data/db